@echo off
echo Starting Brain Tumor Detection Application...

echo Starting Backend Server...
start cmd /k "cd backend && python app.py"

echo Starting Frontend Server...
start cmd /k "npm run dev"

echo Both servers are starting. Please wait a moment...
echo Frontend will be available at: http://localhost:5173
echo Backend API will be available at: http://localhost:5000
